// ========================================================
// 1Acre - Haryana Real Estate Marketplace Initial Seed Data
// Includes Agriculture Land, Farm Houses, Luxury Villas, Plots, and Commercial
// ========================================================

window.haryanaDistricts = [
  "Ambala", "Bhiwani", "Charkhi Dadri", "Faridabad", "Fatehabad", "Gurgaon", 
  "Hisar", "Jhajjar", "Jind", "Kaithal", "Karnal", "Kurukshetra", 
  "Mahendragarh", "Nuh", "Palwal", "Panchkula", "Panipat", "Rewari", 
  "Rohtak", "Sirsa", "Sonipat", "Yamunanagar"
];

window.seedProperties = [
  {
    id: "prop-101",
    title: "12 Acre Prime Agriculture Land near Rohtak MDU Bypass",
    description: "High fertility agricultural land with tubewell water connection, 30 ft pakka road connectivity, registry clear, mutation done. Located opposite Maharshi Dayanand University area on Rohtak Delhi road extension.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 24000000,
    price_display: "₹ 2.0 Cr / Acre",
    area: 12,
    unit: "Acre",
    state: "Haryana",
    district: "Rohtak",
    city: "Rohtak",
    village_landmark: "Opp. Maharshi Dayanand University (Mastnath Area)",
    latitude: 28.8955,
    longitude: 76.6066,
    road_width_ft: 30,
    facing: "North-East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Clear Title / Intakal Done",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Chaudhary Rajesh Dahiya",
    seller_phone: "+91 98120 44550",
    seller_email: "rajesh.dahiya@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/agriculture.jpg", "assets/images/hero.jpg"],
    created_at: "2026-07-20"
  },
  {
    id: "prop-102",
    title: "Luxury 2-Acre Gated Farm House near Sohna Road, Gurgaon",
    description: "Ultra-luxury Mediterranean style farmhouse featuring 4-bedroom villa, private swimming pool, landscaped gardens, 24/7 security, dual borewell water, solar power backup.",
    category: "Residential",
    subcategory: "Farm House",
    price: 95000000,
    price_display: "₹ 9.5 Crore",
    area: 2,
    unit: "Acre",
    state: "Haryana",
    district: "Gurgaon",
    city: "Gurgaon",
    village_landmark: "Sohna Road - KMP Expressway Junction",
    latitude: 28.3245,
    longitude: 77.0315,
    road_width_ft: 40,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry & Mutation Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Broker",
    seller_name: "Sharma & Associates Realty",
    seller_phone: "+91 99991 22334",
    seller_email: "gurgaon@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/farmhouse.jpg", "assets/images/hero.jpg"],
    created_at: "2026-07-22"
  },
  {
    id: "prop-103",
    title: "5 Acre Highway Facing Land on Rohtak-Sonipat Expressway",
    description: "Commercial potential agricultural land directly attached to 60 ft wide state highway. Ideal for petrol pump, cold storage, warehousing or institution.",
    category: "Agriculture",
    subcategory: "Farming Investment Land",
    price: 17500000,
    price_display: "₹ 1.75 Cr / Acre",
    area: 5,
    unit: "Acre",
    state: "Haryana",
    district: "Rohtak",
    city: "Rohtak",
    village_landmark: "Sonipat Road Highway",
    latitude: 28.9300,
    longitude: 76.6300,
    road_width_ft: 60,
    facing: "North",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Vikram Singh Malik",
    seller_phone: "+91 98960 11223",
    seller_email: "vikram.malik@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-24"
  },
  {
    id: "prop-104",
    title: "Luxury 5 BHK Villa in Golf Course Extension, Gurgaon",
    description: "Architectural masterpiece villa spanning 500 Sq. Yd. plot with private elevator, home theater, Italian marble flooring, and smart home automation.",
    category: "Residential",
    subcategory: "Villa",
    price: 68000000,
    price_display: "₹ 6.8 Crore",
    area: 500,
    unit: "Square Yard",
    state: "Haryana",
    district: "Gurgaon",
    city: "Gurgaon",
    village_landmark: "Sector 65, Golf Course Ext Road",
    latitude: 28.4000,
    longitude: 77.0800,
    road_width_ft: 40,
    facing: "North-East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Freehold Registry Clear",
    loan_availability: true,
    ownership_type: "Developer",
    seller_type: "Builder",
    seller_name: "Imperia Builders Gurgaon",
    seller_phone: "+91 98110 55443",
    seller_email: "imperia@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/farmhouse.jpg", "assets/images/hero.jpg"],
    created_at: "2026-07-25"
  },
  {
    id: "prop-105",
    title: "18 Bigha Fertile Land in Jhajjar - Bahadurgarh Belt",
    description: "Organic farming land with active tube-well, fenced perimeter, and easy connectivity to KMP expressway corridor.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 16200000,
    price_display: "₹ 9 Lakh / Bigha",
    area: 18,
    unit: "Bigha",
    state: "Haryana",
    district: "Jhajjar",
    city: "Jhajjar",
    village_landmark: "Bahadurgarh Road",
    latitude: 28.6000,
    longitude: 76.6500,
    road_width_ft: 22,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Intakal Complete",
    loan_availability: true,
    ownership_type: "Joint Family",
    seller_type: "Owner",
    seller_name: "Ramphal Kadian",
    seller_phone: "+91 94160 33221",
    seller_email: "kadian@1acre.in",
    status: "active",
    verification_status: false,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-26"
  },
  {
    id: "prop-106",
    title: "Commercial Industrial Plot near IMT Manesar, Gurgaon",
    description: "HUDA approved industrial & warehouse land plot ready for immediate factory construction with high tension power line access.",
    category: "Commercial",
    subcategory: "Commercial Land",
    price: 45000000,
    price_display: "₹ 4.5 Crore",
    area: 1200,
    unit: "Square Yard",
    state: "Haryana",
    district: "Gurgaon",
    city: "Manesar",
    village_landmark: "IMT Manesar Sector 8",
    latitude: 28.3500,
    longitude: 76.9300,
    road_width_ft: 60,
    facing: "South-East",
    electricity_available: true,
    water_facility: true,
    registry_status: "HUDA Allotment Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Broker",
    seller_name: "National Land Consultants",
    seller_phone: "+91 98180 88776",
    seller_email: "manesar@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/hero.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-107",
    title: "25 Acre Agricultural Farmland in Ambala GT Road Corridor",
    description: "High capacity fertile agricultural soil suitable for wheat, paddy, and sugarcane farming. 2 deep canal borewells, solar transformer connection, and clear title.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 37500000,
    price_display: "₹ 1.5 Cr / Acre",
    area: 25,
    unit: "Acre",
    state: "Haryana",
    district: "Ambala",
    city: "Ambala",
    village_landmark: "GT Road - Saha Highway Link",
    latitude: 30.3782,
    longitude: 76.7767,
    road_width_ft: 35,
    facing: "North",
    electricity_available: true,
    water_facility: true,
    registry_status: "Clear Title / Intakal Done",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Sardarni Harpreet Kaur",
    seller_phone: "+91 98720 11998",
    seller_email: "ambala@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-108",
    title: "15 Acre Fertile Agriculture Plot on Bhiwani Road Corridor",
    description: "Sweet water borewell land with drip irrigation installed. Excellent road connectivity near Tosham bypass in Bhiwani district.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 18000000,
    price_display: "₹ 1.2 Cr / Acre",
    area: 15,
    unit: "Acre",
    state: "Haryana",
    district: "Bhiwani",
    city: "Bhiwani",
    village_landmark: "Tosham Road Junction",
    latitude: 28.7932,
    longitude: 76.1390,
    road_width_ft: 30,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Sunil Kumar Sheoran",
    seller_phone: "+91 94162 88220",
    seller_email: "bhiwani@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-109",
    title: "10 Acre Canal Irrigated Agriculture Land in Charkhi Dadri",
    description: "Flat level agricultural land touching canal minor line. Intakal registry clear, single owner plot near Dadri-Bhiwani highway.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 14000000,
    price_display: "₹ 1.4 Cr / Acre",
    area: 10,
    unit: "Acre",
    state: "Haryana",
    district: "Charkhi Dadri",
    city: "Charkhi Dadri",
    village_landmark: "Bond Kalan Bypass",
    latitude: 28.5921,
    longitude: 76.2653,
    road_width_ft: 25,
    facing: "North-West",
    electricity_available: true,
    water_facility: true,
    registry_status: "Intakal Complete",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Mahender Singh Sangwan",
    seller_phone: "+91 98130 77112",
    seller_email: "dadri@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-110",
    title: "3 Acre Highway Commercial Plot on Mathura Road, Faridabad",
    description: "Prime Delhi NCR commercial highway plot near Ballabhgarh bypass. Ideal for showroom, warehouse, hotel or logistics park.",
    category: "Commercial",
    subcategory: "Commercial Land",
    price: 120000000,
    price_display: "₹ 12.0 Crore",
    area: 3,
    unit: "Acre",
    state: "Haryana",
    district: "Faridabad",
    city: "Faridabad",
    village_landmark: "Mathura Road - Ballabhgarh Belt",
    latitude: 28.3312,
    longitude: 77.3178,
    road_width_ft: 80,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Commercial CLU Approved",
    loan_availability: true,
    ownership_type: "Company",
    seller_type: "Broker",
    seller_name: "NCR Prime Properties",
    seller_phone: "+91 98101 22339",
    seller_email: "faridabad@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/hero.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-111",
    title: "20 Acre Cotton & Paddy Farming Land in Fatehabad",
    description: "High yield cotton & paddy farmland with Bhakra canal water supply, dual submersible tube-well motors, and pacca paved road connection.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 26000000,
    price_display: "₹ 1.3 Cr / Acre",
    area: 20,
    unit: "Acre",
    state: "Haryana",
    district: "Fatehabad",
    city: "Fatehabad",
    village_landmark: "Tohana Road Link",
    latitude: 29.5152,
    longitude: 75.4542,
    road_width_ft: 30,
    facing: "North",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Gurdev Singh Gill",
    seller_phone: "+91 94165 44881",
    seller_email: "fatehabad@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-112",
    title: "30 Acre Agricultural Land near Hisar International Airport Zone",
    description: "Strategic investment land located 10 km from Maharaja Agrasen International Airport, Hisar. High future commercial zone appreciation.",
    category: "Agriculture",
    subcategory: "Farming Investment Land",
    price: 45000000,
    price_display: "₹ 1.5 Cr / Acre",
    area: 30,
    unit: "Acre",
    state: "Haryana",
    district: "Hisar",
    city: "Hisar",
    village_landmark: "Airport Corridor - Sirsa Highway",
    latitude: 29.1793,
    longitude: 75.7229,
    road_width_ft: 50,
    facing: "North-East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Clear Title / Intakal Done",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Chaudhary Devender Bishnoi",
    seller_phone: "+91 98125 99001",
    seller_email: "hisar@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/hero.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-113",
    title: "14 Acre Rice & Wheat Cultivation Farmland in Jind",
    description: "Top grade agricultural soil in Central Haryana belt. Excellent water table level, 3-phase agricultural power connection, and road connectivity.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 18200000,
    price_display: "₹ 1.3 Cr / Acre",
    area: 14,
    unit: "Acre",
    state: "Haryana",
    district: "Jind",
    city: "Jind",
    village_landmark: "Safidon Road Highway",
    latitude: 29.3150,
    longitude: 76.3150,
    road_width_ft: 25,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Rajbir Singh Redhu",
    seller_phone: "+91 94161 55667",
    seller_email: "jind@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-114",
    title: "16 Acre Tubewell Irrigated Agriculture Plot in Kaithal",
    description: "Premium basmati rice growing farmland in Kaithal district. Single owner clear title with 2 electric borewell pumps.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 22400000,
    price_display: "₹ 1.4 Cr / Acre",
    area: 16,
    unit: "Acre",
    state: "Haryana",
    district: "Kaithal",
    city: "Kaithal",
    village_landmark: "Pundri Road Link",
    latitude: 29.8015,
    longitude: 76.4020,
    road_width_ft: 30,
    facing: "North",
    electricity_available: true,
    water_facility: true,
    registry_status: "Intakal Complete",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Surinder Surjewala",
    seller_phone: "+91 98961 44332",
    seller_email: "kaithal@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-115",
    title: "8 Acre Highway Facing Agro-Industrial Land in Karnal GT Road",
    description: "Prime location land directly facing NH-44 (GT Road) in Karnal. Ideal for cold storage, food processing plant, or resort.",
    category: "Commercial",
    subcategory: "Commercial Land",
    price: 48000000,
    price_display: "₹ 6.0 Cr / Acre",
    area: 8,
    unit: "Acre",
    state: "Haryana",
    district: "Karnal",
    city: "Karnal",
    village_landmark: "GT Road - Gharaunda Highway Belt",
    latitude: 29.6857,
    longitude: 76.9905,
    road_width_ft: 100,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Freehold Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Broker",
    seller_name: "GT Road Realty Experts",
    seller_phone: "+91 98131 88990",
    seller_email: "karnal@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/hero.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-116",
    title: "12 Acre Sacred Belt Organic Farm Land in Kurukshetra",
    description: "Highly fertile agricultural parcel in Pipli-Kurukshetra highway corridor. Rich groundwater, solar pump setup, and calm environment.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 19200000,
    price_display: "₹ 1.6 Cr / Acre",
    area: 12,
    unit: "Acre",
    state: "Haryana",
    district: "Kurukshetra",
    city: "Kurukshetra",
    village_landmark: "Pipli Highway Junction",
    latitude: 29.9695,
    longitude: 76.8783,
    road_width_ft: 35,
    facing: "North-East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Jasbir Singh Saini",
    seller_phone: "+91 94163 11889",
    seller_email: "kurukshetra@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-117",
    title: "22 Acre Agricultural Land in Mahendragarh - Narnaul Belt",
    description: "Clear title agricultural plot with sweet borewell water, solar fence, and direct connectivity to Delhi-Mumbai Expressway feeder road.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 22000000,
    price_display: "₹ 1.0 Cr / Acre",
    area: 22,
    unit: "Acre",
    state: "Haryana",
    district: "Mahendragarh",
    city: "Narnaul",
    village_landmark: "Narnaul Bypass Road",
    latitude: 28.0444,
    longitude: 76.1084,
    road_width_ft: 30,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Intakal Complete",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Rameshwar Prasad Yadav",
    seller_phone: "+91 98124 33441",
    seller_email: "narnaul@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-118",
    title: "6 Acre Scenic Farmhouse Plot in Nuh / Aravalli Foothills",
    description: "Picturesque land nestled against the Aravalli hills in Nuh district near Gurgaon border. Ideal for organic farm estate or weekend sanctuary.",
    category: "Residential",
    subcategory: "Farm House",
    price: 27000000,
    price_display: "₹ 45 Lakh / Acre",
    area: 6,
    unit: "Acre",
    state: "Haryana",
    district: "Nuh",
    city: "Nuh",
    village_landmark: "Sohna-Nuh Highway Boundary",
    latitude: 28.1090,
    longitude: 77.0160,
    road_width_ft: 40,
    facing: "North",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Broker",
    seller_name: "Aravalli Valley Land Corp",
    seller_phone: "+91 98112 77889",
    seller_email: "nuh@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/farmhouse.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-119",
    title: "4 Acre KMP Expressway Linked Industrial Land in Palwal",
    description: "Industrial development plot situated along Palwal KMP Interchange. Direct access for heavy logistics, manufacturing, or warehousing.",
    category: "Commercial",
    subcategory: "Commercial Land",
    price: 36000000,
    price_display: "₹ 90 Lakh / Acre",
    area: 4,
    unit: "Acre",
    state: "Haryana",
    district: "Palwal",
    city: "Palwal",
    village_landmark: "Palwal - KMP Expressway Toll",
    latitude: 28.1487,
    longitude: 77.3320,
    road_width_ft: 60,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "CLU Applied / Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Chaudhary Brijmohan Tewatia",
    seller_phone: "+91 98189 33221",
    seller_email: "palwal@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/hero.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-120",
    title: "1.5 Acre Luxury Hillside Farmhouse in Panchkula Extension",
    description: "Exclusive luxury plot with Shivalik hill views in Panchkula extension near Pinjore. Gated community access, lush greenery, and fresh air.",
    category: "Residential",
    subcategory: "Farm House",
    price: 42000000,
    price_display: "₹ 4.2 Crore",
    area: 1.5,
    unit: "Acre",
    state: "Haryana",
    district: "Panchkula",
    city: "Panchkula",
    village_landmark: "Pinjore - Kalka Urban Expressway",
    latitude: 30.6942,
    longitude: 76.8606,
    road_width_ft: 40,
    facing: "North-East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Freehold Clear Title",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Broker",
    seller_name: "Shivalik Greens Real Estate",
    seller_phone: "+91 98760 99887",
    seller_email: "panchkula@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/farmhouse.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-121",
    title: "10 Acre Textile & Warehousing Commercial Land in Panipat",
    description: "Prime industrial land touching Panipat-Rohtak highway near Textile Hub. Perfect for export warehouse, spinning mill, or industrial park.",
    category: "Commercial",
    subcategory: "Commercial Land",
    price: 65000000,
    price_display: "₹ 6.5 Cr / Acre",
    area: 10,
    unit: "Acre",
    state: "Haryana",
    district: "Panipat",
    city: "Panipat",
    village_landmark: "Rohtak Road Industrial Zone",
    latitude: 29.3909,
    longitude: 76.9635,
    road_width_ft: 60,
    facing: "North",
    electricity_available: true,
    water_facility: true,
    registry_status: "Industrial Zoning Clear",
    loan_availability: true,
    ownership_type: "Company",
    seller_type: "Broker",
    seller_name: "Panipat Land Promoters",
    seller_phone: "+91 98122 55667",
    seller_email: "panipat@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/hero.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-122",
    title: "7 Acre Highway Commercial Land on Delhi-Jaipur HW, Rewari",
    description: "Direct frontage plot on NH-48 (Delhi-Jaipur Highway) near Dharuhera-Rewari junction. High traffic density, suitable for motel or logistics.",
    category: "Commercial",
    subcategory: "Commercial Land",
    price: 49000000,
    price_display: "₹ 7.0 Cr / Acre",
    area: 7,
    unit: "Acre",
    state: "Haryana",
    district: "Rewari",
    city: "Rewari",
    village_landmark: "Dharuhera Industrial Corridor",
    latitude: 28.1833,
    longitude: 76.6167,
    road_width_ft: 80,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry & Mutation Done",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Captain Rao Narendra Singh",
    seller_phone: "+91 98133 44112",
    seller_email: "rewari@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/hero.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-123",
    title: "40 Acre Premier Irrigation Agriculture Land in Sirsa",
    description: "Massive agricultural land holding in Sirsa district with canal water share, 4 tubewell points, and high agricultural crop returns.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 48000000,
    price_display: "₹ 1.2 Cr / Acre",
    area: 40,
    unit: "Acre",
    state: "Haryana",
    district: "Sirsa",
    city: "Sirsa",
    village_landmark: "Dabwali Road Highway Link",
    latitude: 29.5320,
    longitude: 75.0318,
    road_width_ft: 30,
    facing: "North-West",
    electricity_available: true,
    water_facility: true,
    registry_status: "Clear Title / Single Owner",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Sardar Baldev Singh Sidhu",
    seller_phone: "+91 94168 77001",
    seller_email: "sirsa@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-124",
    title: "15 Acre GT Road Facing Agricultural Land in Sonipat",
    description: "Prime farmland near Rai Educational City and KMP Interchange. High commercial appreciation potential along GT Karnal road corridor.",
    category: "Agriculture",
    subcategory: "Farming Investment Land",
    price: 33000000,
    price_display: "₹ 2.2 Cr / Acre",
    area: 15,
    unit: "Acre",
    state: "Haryana",
    district: "Sonipat",
    city: "Sonipat",
    village_landmark: "Rai Industrial Area Link",
    latitude: 28.9931,
    longitude: 77.0151,
    road_width_ft: 45,
    facing: "East",
    electricity_available: true,
    water_facility: true,
    registry_status: "Registry Clear",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Broker",
    seller_name: "Sonipat Realty Hub",
    seller_phone: "+91 98121 66554",
    seller_email: "sonipat@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: true,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  },
  {
    id: "prop-125",
    title: "18 Acre Plywood & Agro-Forestry Land in Yamunanagar",
    description: "High fertile land ideal for Poplar timber & agricultural crops in Yamunanagar. Yamuna canal irrigation channel, paved access road.",
    category: "Agriculture",
    subcategory: "Agricultural Land",
    price: 23400000,
    price_display: "₹ 1.3 Cr / Acre",
    area: 18,
    unit: "Acre",
    state: "Haryana",
    district: "Yamunanagar",
    city: "Yamunanagar",
    village_landmark: "Jagadhri Highway Corridor",
    latitude: 30.1290,
    longitude: 77.2674,
    road_width_ft: 30,
    facing: "North",
    electricity_available: true,
    water_facility: true,
    registry_status: "Intakal Complete",
    loan_availability: true,
    ownership_type: "Single Owner",
    seller_type: "Owner",
    seller_name: "Praveen Kumar Kamboj",
    seller_phone: "+91 94164 22110",
    seller_email: "yamunanagar@1acre.in",
    status: "active",
    verification_status: true,
    is_featured: false,
    images: ["assets/images/agriculture.jpg"],
    created_at: "2026-07-27"
  }
];


window.seedBlogs = [
  {
    id: "blog-1",
    title: "Complete Guide to Haryana Land Registry (Jamabandi & Intakal Process)",
    slug: "haryana-land-registry-jamabandi-intakal-guide",
    category: "Registry Process",
    author: "Legal & Legal Verification Cell - 1Acre",
    image: "assets/images/hero.jpg",
    seo_title: "Haryana Jamabandi & Intakal Land Registry Process Guide",
    seo_description: "Learn how to verify land ownership documents, Jamabandi online portal, collector rates, and Intakal mutation process in Rohtak and Gurgaon.",
    created_at: "2026-07-15",
    content: `
      <h3>Understanding Land Ownership Records in Haryana</h3>
      <p>Before purchasing agricultural land or farmhouses in Haryana, understanding the digital land record system (Web-HALRIS and Jamabandi portal) is essential.</p>
      <h4>Key Legal Documents Required:</h4>
      <ul>
        <li><strong>Jamabandi (Record of Rights):</strong> Proves current legal ownership and killa numbers.</li>
        <li><strong>Intakal (Mutation):</strong> Updates government records after sale deed registration.</li>
        <li><strong>Aksh Shajra (Map):</strong> Physical map showing exact land layout and road access width.</li>
      </ul>
      <p>At 1Acre, our ground teams inspect every listed property for clear title, non-encumbrance certificates, and registry readiness before assigning the '1Acre Verified' badge.</p>
    `
  },
  {
    id: "blog-2",
    title: "Why Investing in Rohtak & KMP Expressway Land Yields High Returns",
    slug: "investing-in-rohtak-kmp-expressway-land-trends",
    category: "Land Investment",
    author: "Haryana Market Research Group",
    image: "assets/images/agriculture.jpg",
    seo_title: "Rohtak Property Investment Trends & Land Price Growth",
    seo_description: "Explore land price growth around Rohtak MDU bypass, Delhi road corridor, and Sonipat KMP Expressway interchange.",
    created_at: "2026-07-18",
    content: `
      <h3>The Growth Corridor of Haryana</h3>
      <p>Rohtak has emerged as a premier educational, medical, and industrial hub in Haryana. With rapid connectivity via Delhi-Rohtak Elevated Expressway and KMP bypass, land demand around MDU, Mastnath, and Sonipat Road has surged by 35% year-on-year.</p>
      <h4>Top 3 High-Growth Zones in Rohtak:</h4>
      <ol>
        <li><strong>Mastnath / MDU Area:</strong> High demand for institutional and commercial farmland.</li>
        <li><strong>Delhi Bypass Corridor:</strong> Premier residential plots and luxury farmhouse estates.</li>
        <li><strong>Karkhana Road & Sonipat Highway:</strong> Warehousing and agricultural investment land.</li>
      </ol>
    `
  }
];
